// Generate ui/public/favicon.svg from the Marquee mark — the same paper-on-ink tile the desktop app
// icon uses ([ADR 0091](../../../docs/adrs/0091-the-app-icon-and-the-masthead-mark-are-the-logo.md)).
//
// **This is not the app's icon.** Curator ships as a single-window Electron app with no browser tab
// (curator-ui-ux §2, and curator-spec is emphatic about it); the window and taskbar icon is
// packages/desktop/build/icon.png. This file is for the other two ways Curator gets opened, both of
// which are documented workflows and both of which showed a default icon until now: the Vite dev
// server on :4738, and pointing a real browser at the served UI on :4739.
//
// It carries explicit fills rather than `currentColor` because a favicon is a standalone document
// with nothing to inherit from, and it keeps the tile because the surrounding chrome may be light or
// dark and the mark is thin line art.
//
// SVG in, SVG out — the mark's path data is reused verbatim under a transform, never re-emitted, so
// this cannot drift from the source the way a hand-copied second file would. `buildFavicon()` is
// exported (and unit-tested); the file writes only when run directly.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath, pathToFileURL } from "node:url";
import { dirname, join, resolve } from "node:path";

const HERE = dirname(fileURLToPath(import.meta.url));

/** The one copy of the mark — the same file the masthead inlines and the app icon rasterizes. */
export const MARK_SVG = resolve(
  HERE,
  "..",
  "ui",
  "src",
  "assets",
  "marquee-mark.svg",
);
export const FAVICON_SVG = resolve(HERE, "..", "ui", "public", "favicon.svg");

// Kept in step with packages/desktop/scripts/make-icon.mjs — the two are one icon in two formats.
const N = 512; // the favicon's own coordinate space
const INSET = 0.8; // fraction of the tile the mark spans on its longer axis
const TILE_HALF = 0.46; // rounded-square half-extent, in normalized units
const TILE_RADIUS = 0.14; // its corner radius, same units

const INK = "#17150f"; // the tile — Pressing Plant `--pp-ink`
const PAPER = "#f2efe8"; // the mark — `--pp-paper`

const round = (n, places = 2) => +(Math.round(n * 10 ** places) / 10 ** places);

/**
 * Throw if `svg` contains an XML comment XML will not accept. A favicon is served as a standalone
 * file and parsed as strict XML, not swept up by an HTML parser, so an illegal comment is not a
 * nitpick — Chromium renders the parser error where the icon should be.
 *
 * This exists because it happened: the header below once read "pnpm --filter …", the `--` made the
 * file invalid, and every string assertion in the test suite still passed. jsdom's DOMParser is too
 * lenient to catch it, so the rule is checked directly.
 */
export function assertXmlComments(svg) {
  for (const [, body] of svg.matchAll(/<!--([\s\S]*?)-->/g)) {
    if (body.includes("--"))
      throw new Error(
        `make-favicon: XML comments must not contain "--" — found in: ${body.trim().slice(0, 80)}`,
      );
    if (body.endsWith("-"))
      throw new Error(
        `make-favicon: XML comments must not end with "-" — found in: ${body.trim().slice(0, 80)}`,
      );
  }
  return svg;
}

/**
 * The favicon's SVG source, built from the mark. `markSource` defaults to the mark on disk; passing
 * it lets the test drive the guards below without a fixture file.
 */
export function buildFavicon(markSource = readFileSync(MARK_SVG, "utf8")) {
  const svg = markSource;

  const viewBox = svg.match(/viewBox="0 0 ([\d.]+) ([\d.]+)"/);
  if (!viewBox) throw new Error(`make-favicon: no viewBox in ${MARK_SVG}`);
  const markW = Number(viewBox[1]);
  const markH = Number(viewBox[2]);

  const paths = [...svg.matchAll(/<path[^>]*\sd="([^"]+)"/g)].map((m) => m[1]);
  if (!paths.length) throw new Error(`make-favicon: no paths in ${MARK_SVG}`);

  // Fit the mark into the inset box and centre it. The mark is taller than it is wide, so which
  // axis binds is computed, not assumed.
  const scale = Math.min((N * INSET) / markW, (N * INSET) / markH);
  const tx = round((N - markW * scale) / 2);
  const ty = round((N - markH * scale) / 2);

  const side = round(N * TILE_HALF * 2);
  const origin = round(N * (0.5 - TILE_HALF));
  const radius = round(N * TILE_RADIUS);

  return assertXmlComments(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${N} ${N}">
  <!-- Generated by scripts/make-favicon.mjs from src/assets/marquee-mark.svg. Do not edit by hand.
       Regenerate with the package's \`favicon\` script; a test fails if it is stale. Everywhere else
       spells that as a repo-root pnpm filter command; it cannot be written here, because the flag
       that selects a package contains the one character sequence an XML comment may not. -->
  <rect x="${origin}" y="${origin}" width="${side}" height="${side}" rx="${radius}" fill="${INK}"/>
  <g transform="translate(${tx} ${ty}) scale(${round(scale, 6)})" fill="${PAPER}" fill-rule="nonzero">
${paths.map((d) => `    <path d="${d}"/>`).join("\n")}
  </g>
</svg>
`);
}

// Write only when run directly (`node scripts/make-favicon.mjs`), not when imported by the test.
if (
  process.argv[1] &&
  import.meta.url === pathToFileURL(process.argv[1]).href
) {
  const out = buildFavicon();
  mkdirSync(dirname(FAVICON_SVG), { recursive: true });
  writeFileSync(FAVICON_SVG, out);
  console.log(
    `✓ wrote ${join("ui", "public", "favicon.svg")} (${out.length} bytes)`,
  );
}
